# Generated by Django 5.1.8 on 2025-05-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="permisos",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios", to="usuarios.permiso"
            ),
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                (
                    "permisos",
                    models.ManyToManyField(related_name="roles", to="usuarios.permiso"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="roles",
            field=models.ManyToManyField(related_name="usuarios", to="usuarios.rol"),
        ),
    ]
