# Generated by Django 5.1.8 on 2025-05-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_permisos_rol_usuario_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={},
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios", to="usuarios.rol"
            ),
        ),
    ]
