# Generated by Django 5.1.8 on 2025-05-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="permisos",
        ),
    ]
