# Generated by Django 5.1.8 on 2025-05-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_remove_usuario_permisos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rol",
            name="permisos",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="roles",
        ),
        migrations.DeleteModel(
            name="Permiso",
        ),
        migrations.DeleteModel(
            name="Rol",
        ),
    ]
