# Generated by Django 5.1.8 on 2025-07-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_remove_rol_permisos_remove_usuario_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(max_length=50),
        ),
    ]
